AWSTemplateFormatVersion: 2010-09-09
Description: CDN for Arizona Digital
Parameters:
  CDNCert:
    Type: String
    Description: The ARN of the certificate uploaded to ACM in us-east-1
  CDNDomain:
    Type: String
    Description: The domain for the Arizona Digital CDN
  CDNTTL:
    Type: Number
    Default: 3600
    Description: The defualt TTL for the cloudfront distribution
Resources:
  CDNBucket:
    Type: AWS::S3::Bucket
    # Properties:
    #   WebsiteConfiguration:
    #     IndexDocument: index.html
    #     ErrorDocument: error.html

  CDNBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
        PolicyDocument:
          Id: CDNBucketOriginPolicy
          Version: 2012-10-17
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: !Sub "arn:aws:s3:::${CDNBucket}/*"
        Bucket: !Ref CDNBucket

  CDNBucketOriginOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "CDNBucketOriginOAI"

  CDNCIGroup:
    Type: AWS::IAM::Group

  CDNCIPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "ArizonaDigitalCDNCIPolicy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource:
              - !Sub "arn:aws:s3:::${CDNBucket}/*"
          -
            Effect: "Allow"
            Action:
              - "s3:ListBucket"
            Resource:
              - !Sub "arn:aws:s3:::${CDNBucket}"
          -
            Effect: "Allow"
            Action:
              - "cloudfront:CreateInvalidation"
            Resource: "*"
      Groups:
        - !Ref CDNCIGroup

  CDNDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Aliases:
          - !Ref CDNDomain
        Enabled: "true"
        PriceClass: PriceClass_All
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref CDNCert
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
        Origins:
          - DomainName: !Sub "${CDNBucket}.s3.amazonaws.com"
            Id: CDNBucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CDNBucketOriginOAI}"
        DefaultCacheBehavior:
          DefaultTTL: !Ref CDNTTL
          Compress: "true"
          TargetOriginId: CDNBucketOrigin
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
